with Ada.Text_IO;
use Ada.Text_IO;
with Ada.Integer_Text_IO; 
use Ada.Integer_Text_IO;
with complex;
use complex;

procedure main is 
	num1: number := (2,3);
	num2: number := (2,6);
	number1real: Integer;
	number1imag: Integer;
	number2real: Integer;
	number2imag: Integer;
begin
	Put_Line("===================TEST CASE===================");
	show(num1, num2);
	New_Line;
	Put_Line("Addition:   ");
	add(num1, num2);
	New_Line;
	Put_Line("Subtraction:   ");
	subtract(num1, num2);
	New_Line;
	Put_Line("Multiplication:   ");
	multiply(num1, num2);
	New_Line;
	Put_Line("Division:   ");
	divide(num1, num2);
	Put_Line("===================TEST CASE===================");
	Put("Enter Number One's Real: ");
	Get(number1real);
	num1.real := number1real;
	Put("Enter Number One's Imaginary: ");
	Get(number1imag);
	num1.imaginary := number1imag;
	Put("Enter Number Two's Real: ");
	Get(number2real);
	num2.real := number2real;
	Put("Enter Number Two's Imaginary: ");
	Get(number2imag);
	num2.imaginary := number2imag;
	Put_Line("===================USER CASE===================");
	show(num1, num2);
	New_Line;
	Put_Line("Addition:   ");
	add(num1, num2);
	New_Line;
	Put_Line("Subtraction:   ");
	subtract(num1, num2);
	New_Line;
	Put_Line("Multiplication:   ");
	multiply(num1, num2);
	New_Line;
	Put_Line("Division:   ");
	divide(num1, num2);
	Put_Line("===================USER CASE===================");
end main;
